// Shared game + voice types.
//
// Originally a Day-2 stub hosting the voice-adjacent type aliases (Rank,
// Persona, TruthState, Card, VoiceSettings, VoiceMeta, RoundDeal). Extended
// Day 3 per game-engine spec §2 + Task 1.1 to carry the full FSM type layer:
// Claim/PublicClaim, Round, PlayerState, Session, Client* projections, the
// GameEvent discriminated union, and the InvalidTransitionError class.
//
// All types here are pure data shapes — no runtime behavior lives in this
// file; the reducer and projections are in `fsm.ts` / `toClientView.ts`.

// ---------------------------------------------------------------------------
// Primitive aliases
// ---------------------------------------------------------------------------

export type Rank = 'Queen' | 'King' | 'Ace' | 'Jack';
export type Persona = 'Novice' | 'Reader' | 'Misdirector' | 'Silent';
export type TruthState = 'honest' | 'lying';
export type JokerType =
  | 'poker_face'
  | 'stage_whisper'
  | 'earful'
  | 'cold_read'
  | 'second_wind';

// ---------------------------------------------------------------------------
// Card
// ---------------------------------------------------------------------------

export interface Card {
  /** Stable per session — `${rank}-${i}` where i ∈ 0..4. e.g. `Queen-0`, `King-3`. Generated by `deck-and-claims` / `makeDeck()`. */
  id: string;
  rank: Rank;
}

// ---------------------------------------------------------------------------
// Voice (owned by voice-tell-taxonomy spec; re-exported here for FSM use)
// ---------------------------------------------------------------------------

/**
 * Matches ElevenLabs `voiceSettings` payload for Flash v2.5. Property names
 * are snake_case to mirror the API — we pass this verbatim into the
 * `voiceSettings` field of `textToSpeech.convert()` after a shape adapter
 * (SDK uses camelCase on its typed surface).
 */
export interface VoiceSettings {
  stability: number; // [0, 1]
  similarity_boost: number; // [0, 1]
  style: number; // [0, 1]
  speed: number; // ~[0.9, 1.1]
}

export interface VoiceMeta {
  latencyMs: number;
  fillerCount: number;
  pauseCount: number;
  speechRateWpm: number;
  /** 0..1 normalized. See voice-tell-taxonomy spec §3. */
  lieScore: number;
  /** null = unparseable — triggers the caller-side retry UI. */
  parsed: { count: number; rank: Rank } | null;
}

// ---------------------------------------------------------------------------
// Claims (server-side full; client-side public projection)
// ---------------------------------------------------------------------------

export interface Claim {
  by: 'player' | 'ai';
  /** Always 1 or 2 (spec §1.3). */
  count: number;
  claimedRank: Rank;
  /** SERVER-ONLY — stripped by toClientView for opponent's view. */
  actualCardIds: string[];
  /** Derived server-side from actualCardIds vs claimedRank. */
  truthState: TruthState;
  /** Player claims only. */
  voiceMeta?: VoiceMeta;
  /** AI claims only. */
  ttsSettings?: VoiceSettings;
  /** AI claims only — preserved on own-viewer side for Earful autopsy UI. */
  llmReasoning?: string;
  /** Optional dialogue variant the TTS layer spoke. */
  claimText?: string;
  timestamp: number;
}

export interface PublicClaim {
  by: 'player' | 'ai';
  count: number;
  claimedRank: Rank;
  claimText?: string;
  timestamp: number;
}

// ---------------------------------------------------------------------------
// Round
// ---------------------------------------------------------------------------

export interface ActiveJokerEffect {
  type: JokerType;
  expiresAfter: 'next_claim' | 'next_challenge' | 'session';
}

export interface Round {
  roundNumber: 1 | 2 | 3;
  targetRank: Rank;
  activePlayer: 'player' | 'ai';
  pile: Card[];
  claimHistory: Claim[];
  status: 'claim_phase' | 'response_phase' | 'resolving' | 'round_over';
  activeJokerEffects: ActiveJokerEffect[];
  /** 0..1 — consumed by tension-music-system spec. */
  tensionLevel: number;
  winner?: 'player' | 'ai';
}

// ---------------------------------------------------------------------------
// Player + Session
// ---------------------------------------------------------------------------

export interface PlayerState {
  hand: Card[];
  /** Cards this player took after losing a challenge. Public info — opponent saw the pile transfer. */
  takenCards: Card[];
  roundsWon: number;
  /** 0..3 — session ends the instant this hits 3 (opponent wins). */
  strikes: number;
  jokers: JokerType[];
  personaIfAi?: Persona;
}

export interface MusicTrack {
  level: 'calm' | 'tense' | 'critical';
  url: string;
}

export interface Session {
  id: string;
  player: PlayerState;
  ai: PlayerState;
  /** 10 undealt cards for the current round. After SetupComplete and after JokerPicked, length === 10. */
  deck: Card[];
  rounds: Round[];
  currentRoundIdx: number;
  status: 'setup' | 'round_active' | 'joker_offer' | 'session_over';
  sessionWinner?: 'player' | 'ai';
  musicTracks: MusicTrack[];
}

// ---------------------------------------------------------------------------
// Client projections (wire format)
// ---------------------------------------------------------------------------

/** Opponent keeps `takenCards` (public info) but `hand` is replaced with `handSize`. */
export type ClientOpponent = Omit<PlayerState, 'hand'> & { handSize: number };

export interface ClientRound extends Omit<Round, 'claimHistory' | 'pile'> {
  claimHistory: PublicClaim[];
  pileSize: number;
}

export interface ClientSession {
  id: string;
  self: PlayerState;
  opponent: ClientOpponent;
  rounds: ClientRound[];
  currentRoundIdx: number;
  status: Session['status'];
  sessionWinner?: Session['sessionWinner'];
  currentMusicUrl?: string;
}

// ---------------------------------------------------------------------------
// Auxiliary caller-provided types
// ---------------------------------------------------------------------------

/**
 * Produced by `deck-and-claims` / `dealFresh()`, consumed by the reducer via
 * SetupComplete and JokerPicked events. Caller owns all randomness.
 *
 * Invariant: playerHand (5) + aiHand (5) + remainingDeck (10) === all 20
 * unique Cards.
 */
export interface RoundDeal {
  playerHand: Card[];
  aiHand: Card[];
  remainingDeck: Card[];
  targetRank: Rank;
  activePlayer: 'player' | 'ai';
}

// ---------------------------------------------------------------------------
// GameEvent discriminated union
// ---------------------------------------------------------------------------
//
// Every event carries `now` so the reducer never reads Date.now() directly.
// SetupComplete and JokerPicked carry caller-provided deals so randomness
// stays out of the reducer too.

export type GameEvent =
  | {
      type: 'SetupComplete';
      now: number;
      initialDeal: RoundDeal;
      musicTracks: MusicTrack[];
    }
  | { type: 'ClaimMade'; claim: Claim; now: number }
  | { type: 'ClaimAccepted'; now: number }
  | { type: 'ChallengeCalled'; now: number }
  | { type: 'RevealComplete'; challengeWasCorrect: boolean; now: number }
  | { type: 'RoundSettled'; now: number }
  | {
      type: 'JokerPicked';
      joker: JokerType;
      nextRoundDeal: RoundDeal;
      now: number;
    }
  | { type: 'JokerOfferSkippedSessionOver'; now: number }
  | {
      type: 'Timeout';
      kind: 'active_player';
      cardIdToPlay: string;
      now: number;
    }
  | { type: 'Timeout'; kind: 'responder'; now: number };

// ---------------------------------------------------------------------------
// Error class
// ---------------------------------------------------------------------------

/**
 * Thrown by the reducer when an event isn't valid in the current Session /
 * Round state (e.g. ClaimAccepted while in `claim_phase`, any event after
 * `session_over`). Never silently no-op.
 */
export class InvalidTransitionError extends Error {
  constructor(
    public readonly currentState: string,
    public readonly eventType: string,
  ) {
    super(
      `Invalid transition: event '${eventType}' not valid in state '${currentState}'`,
    );
    this.name = 'InvalidTransitionError';
  }
}
