// Shared game + voice types.
//
// Originally a Day-2 stub hosting the voice-adjacent type aliases (Rank,
// Persona, TruthState, Card, VoiceSettings, VoiceMeta, RoundDeal). Extended
// Day 3 per game-engine spec §2 + Task 1.1 to carry the full FSM type layer:
// Claim/PublicClaim, Round, PlayerState, Session, Client* projections, the
// GameEvent discriminated union, and the InvalidTransitionError class.
//
// Day-5 pre-land (orchestrator, 2026-04-19) adds OPTIONAL fields for
// joker-system / probe-phase / tension-music-system / Earful autopsy,
// 6 new GameEvent variants (JokerOffered / JokerOfferEmpty / UseJoker /
// ProbeStart / ProbeComplete / ProbeExpired), and 3 new top-level types
// (ActiveProbe / RevealedProbe / ProbeFilterSource). All additions are
// optional so existing tests continue to construct Round/PlayerState/
// Session without providing the new fields; the Day-5 worktrees fill in
// the reducer logic + populate the new slots via the new events.
//
// All types here are pure data shapes — no runtime behavior lives in this
// file; the reducer and projections are in `fsm.ts` / `toClientView.ts`.

// ---------------------------------------------------------------------------
// Re-exports (Day-5 pre-land)
// ---------------------------------------------------------------------------
// Joker slot/offer shapes live in `src/lib/jokers/types.ts` per joker-system
// spec §7.1. We import them here to wire into PlayerState + Session, and
// re-export so downstream code can `import { JokerSlot } from '@/lib/game/types'`.
// `VoiceTellPreset` lives in `src/lib/voice/presets.ts` — same pattern.

import type { JokerSlot, JokerOffer } from '../jokers/types';
import type { VoiceTellPreset } from '../voice/presets';
export type { JokerSlot, JokerOffer } from '../jokers/types';
export type { VoiceTellPreset } from '../voice/presets';

// ---------------------------------------------------------------------------
// Primitive aliases
// ---------------------------------------------------------------------------

export type Rank = 'Queen' | 'King' | 'Ace' | 'Jack';
export type Persona = 'Novice' | 'Reader' | 'Misdirector' | 'Silent';
export type TruthState = 'honest' | 'lying';
export type JokerType =
  | 'poker_face'
  | 'stage_whisper'
  | 'earful'
  | 'cold_read'
  | 'second_wind';

// ---------------------------------------------------------------------------
// Card
// ---------------------------------------------------------------------------

export interface Card {
  /** Stable per session — `${rank}-${i}` where i ∈ 0..4. e.g. `Queen-0`, `King-3`. Generated by `deck-and-claims` / `makeDeck()`. */
  id: string;
  rank: Rank;
}

// ---------------------------------------------------------------------------
// Voice (owned by voice-tell-taxonomy spec; re-exported here for FSM use)
// ---------------------------------------------------------------------------

/**
 * Matches ElevenLabs `voiceSettings` payload for Flash v2.5. Property names
 * are snake_case to mirror the API — we pass this verbatim into the
 * `voiceSettings` field of `textToSpeech.convert()` after a shape adapter
 * (SDK uses camelCase on its typed surface).
 */
export interface VoiceSettings {
  stability: number; // [0, 1]
  similarity_boost: number; // [0, 1]
  style: number; // [0, 1]
  speed: number; // ~[0.9, 1.1]
}

export interface VoiceMeta {
  latencyMs: number;
  fillerCount: number;
  pauseCount: number;
  speechRateWpm: number;
  /** 0..1 normalized. See voice-tell-taxonomy spec §3. */
  lieScore: number;
  /** null = unparseable — triggers the caller-side retry UI. */
  parsed: { count: number; rank: Rank } | null;
}

// ---------------------------------------------------------------------------
// Claims (server-side full; client-side public projection)
// ---------------------------------------------------------------------------

export interface Claim {
  by: 'player' | 'ai';
  /** Always 1 or 2 (spec §1.3). */
  count: number;
  claimedRank: Rank;
  /** SERVER-ONLY — stripped by toClientView for opponent's view. */
  actualCardIds: string[];
  /** Derived server-side from actualCardIds vs claimedRank. */
  truthState: TruthState;
  /** Player claims only. */
  voiceMeta?: VoiceMeta;
  /** AI claims only. */
  ttsSettings?: VoiceSettings;
  /** AI claims only — preserved on own-viewer side for Earful autopsy UI. */
  llmReasoning?: string;
  /** Optional dialogue variant the TTS layer spoke. */
  claimText?: string;
  /**
   * AI claims only — the voice-tell preset active on this TTS turn. Day-5
   * pre-land (joker-system spec §7.4.3 Earful autopsy). Read by the reducer
   * when populating `ClientSession.autopsy` on `ChallengeWon` while Earful
   * is in `activeJokerEffects`. Populated by the AI claim construction site
   * (ai-opponent worktree Day-5).
   */
  voicePreset?: VoiceTellPreset;
  timestamp: number;
}

export interface PublicClaim {
  by: 'player' | 'ai';
  count: number;
  claimedRank: Rank;
  claimText?: string;
  timestamp: number;
  /**
   * Cold Read projection only (joker-system §7.4.2, Task 12).
   * Retained by toClientView on the LAST AI claim when `cold_read` is in
   * `Round.activeJokerEffects`. Stripped on all other claims + all non-Cold-Read rounds.
   * Strictly additive — does not affect any existing PublicClaim construction site.
   *
   * Spec-faithful narrow shape: only `lieScore` crosses the wire. Other
   * VoiceMeta fields (latencyMs, fillerCount, etc.) are server-only and MUST
   * NOT be projected to the client. `buildContexts.ts` carries the full
   * VoiceMeta server-side via an explicit `Omit<PublicClaim,'voiceMeta'> &
   * { voiceMeta?: VoiceMeta }` intersection, independent of this narrow shape.
   */
  voiceMeta?: { lieScore: number };
}

// ---------------------------------------------------------------------------
// Round
// ---------------------------------------------------------------------------

export interface ActiveJokerEffect {
  type: JokerType;
  expiresAfter: 'next_claim' | 'next_challenge' | 'session';
}

// ---------------------------------------------------------------------------
// Probe (Day-5 pre-land — probe-phase spec)
// ---------------------------------------------------------------------------

/** Which internal lane produced the revealed reasoning snippet. Spec §4 + §5. */
export type ProbeFilterSource =
  | 'llm-heuristic-layer'  // structured LLM field (preferred — see §5.2)
  | 'regex-scrub'          // sanitized full llmReasoning (fallback)
  | 'fallback-static';     // filter produced empty output → static template (last-resort)

/**
 * Server-side in-flight probe state. Lives on `Round.activeProbe?` (pseudo-
 * state per game-engine §1.1 — NOT a Round.status enum value). Set by the
 * `ProbeStart` reducer, cleared by `ProbeComplete` / `ProbeExpired`.
 *
 * `rawLlmReasoning` is stripped by toClientView before projecting into
 * `ClientRound.currentProbe`.
 *
 * Spec: probe-phase §4 (LOCKED shape).
 */
export interface ActiveProbe {
  whisperId: string;
  targetAiId: 'ai';
  roundIdx: number;
  triggeredAtTurn: number;
  /** Filtered output safe to show the player. */
  revealedReasoning: string;
  filterSource: ProbeFilterSource;
  /** Server timestamp from the ProbeStart event's `now`. */
  startedAt: number;
  /** Server-authoritative reveal duration; default 4000ms. */
  decayMs: number;
  /** `startedAt + decayMs`. */
  expiresAt: number;
  /** SERVER-ONLY — stripped by toClientView. Never crosses the wire. */
  rawLlmReasoning: string;
}

/** Client-side filtered projection of ActiveProbe. Self-only view. Spec: probe-phase §4. */
export interface RevealedProbe {
  whisperId: string;
  revealedReasoning: string;
  filterSource: ProbeFilterSource;
  decayMs: number;
  expiresAt: number;
}

export interface Round {
  roundNumber: 1 | 2 | 3;
  targetRank: Rank;
  activePlayer: 'player' | 'ai';
  pile: Card[];
  claimHistory: Claim[];
  status: 'claim_phase' | 'response_phase' | 'resolving' | 'round_over';
  activeJokerEffects: ActiveJokerEffect[];
  /** 0..1 — consumed by tension-music-system spec. */
  tensionLevel: number;
  winner?: 'player' | 'ai';
  /**
   * Day-5 pre-land (probe-phase spec). Probe is a PSEUDO-state per
   * game-engine §1.1 — NO `Round.status: 'probing'` value is added. Instead,
   * presence of `activeProbe` on a Round with `status: 'response_phase'` is
   * the derivation key for `ClientSession.phase === 'probe-reveal'`.
   */
  activeProbe?: ActiveProbe;
  /**
   * Day-5 pre-land (joker-system spec §7.1.4). Tracks joker types that fired
   * during this round for invariants and UI state. Worktrees populate.
   */
  jokerTriggeredThisRound?: JokerType[];
  /**
   * Day-5 pre-land (joker-system spec). Non-probe async effects only —
   * Stage Whisper delegates its in-flight state to `activeProbe` above, per
   * orchestrator reconciliation 2026-04-19.
   */
  pendingJokerActivation?: { joker: JokerType; by: 'player' | 'ai' };
}

// ---------------------------------------------------------------------------
// Player + Session
// ---------------------------------------------------------------------------

export interface PlayerState {
  hand: Card[];
  /** Cards this player took after losing a challenge. Public info — opponent saw the pile transfer. */
  takenCards: Card[];
  roundsWon: number;
  /** 0..3 — session ends the instant this hits 3 (opponent wins). */
  strikes: number;
  jokers: JokerType[];
  personaIfAi?: Persona;
  /**
   * Day-5 pre-land (joker-system spec §7.1.5). Authoritative per-player joker
   * slots. Additive — the existing `jokers: JokerType[]` field is kept as a
   * derived alias during migration (joker-system worktree mirrors both fields
   * on `JokerPicked` / `UseJoker`).
   */
  jokerSlots?: JokerSlot[];
}

export interface MusicTrack {
  level: 'calm' | 'tense' | 'critical';
  url: string;
}

export interface Session {
  id: string;
  player: PlayerState;
  ai: PlayerState;
  /** 10 undealt cards for the current round. After SetupComplete and after JokerPicked, length === 10. */
  deck: Card[];
  rounds: Round[];
  currentRoundIdx: number;
  status: 'setup' | 'round_active' | 'joker_offer' | 'session_over';
  sessionWinner?: 'player' | 'ai';
  musicTracks: MusicTrack[];
  /**
   * Day-5 pre-land (joker-system spec §7.1.1). Server-only — stripped by
   * toClientView. Seeded at SetupComplete (caller-provided via optional
   * `initialJokerDrawPile` or reducer default via `seedDrawPile()`).
   */
  jokerDrawPile?: JokerType[];
  /**
   * Day-5 pre-land (joker-system spec §7.1.9). Visible to opponent ONLY
   * when `Session.status !== 'round_active'` per projection gate.
   */
  discardedJokers?: JokerType[];
  /**
   * Day-5 pre-land (joker-system spec §7.1.1). Projected only to the
   * `offeredToWinner` viewer — opponent sees the flash of 2 unpicked
   * jokers land in `discardedJokers` after pick.
   */
  currentOffer?: JokerOffer;
  /**
   * Day-5 pre-land (joker-system spec §7.4.3 — Earful preset-reveal).
   * Set by the `ChallengeWon` reducer when Earful is in the player's
   * `activeJokerEffects`. Cleared on next `ChallengeCalled` or `RoundSettled`.
   * Projected as-is into `ClientSession.autopsy` for the self viewer only.
   */
  autopsy?: { preset: VoiceTellPreset; roundIdx: number; turnIdx: number };
}

// ---------------------------------------------------------------------------
// Client projections (wire format)
// ---------------------------------------------------------------------------

/** Opponent keeps `takenCards` (public info) but `hand` is replaced with `handSize`. */
export type ClientOpponent = Omit<PlayerState, 'hand'> & { handSize: number };

export interface ClientRound
  extends Omit<
    Round,
    | 'claimHistory'
    | 'pile'
    | 'activeProbe'
    | 'jokerTriggeredThisRound'
    | 'pendingJokerActivation'
  > {
  claimHistory: PublicClaim[];
  pileSize: number;
  /**
   * Day-5 pre-land (probe-phase spec §4). Filtered projection of
   * `Round.activeProbe` — `rawLlmReasoning` is stripped; `revealedReasoning`
   * is the filter output that's safe to show the player. The probe-phase
   * worktree populates this via the filter; pre-land leaves it undefined.
   */
  currentProbe?: RevealedProbe;
}

export interface ClientSession {
  id: string;
  self: PlayerState;
  opponent: ClientOpponent;
  rounds: ClientRound[];
  currentRoundIdx: number;
  status: Session['status'];
  sessionWinner?: Session['sessionWinner'];
  currentMusicUrl?: string;
  /**
   * Day-5 pre-land (joker-system Earful preset-reveal). Projected from
   * `Session.autopsy` for the self viewer only. Opponent view has no autopsy.
   */
  autopsy?: { preset: VoiceTellPreset; roundIdx: number; turnIdx: number };
  /**
   * Day-5 pre-land (tension-music-system spec §6.6). Populated client-side
   * (via `useMusicBed` hook state), NOT projected by toClientView. Exposed
   * on ClientSession so React components can react to disabled/muted state.
   */
  musicState?: { disabled: boolean; userMuted: boolean };
  /**
   * Day-5 pre-land (joker-system spec §7.1.9). Projected from
   * `Session.discardedJokers` only when `Session.status !== 'round_active'`
   * (both viewers see it post-round for autopsy UI).
   */
  discardedJokers?: JokerType[];
  /**
   * Day-5 pre-land (joker-system spec §7.1.1). Projected from
   * `Session.currentOffer` only when viewer === `offeredToWinner`.
   * Opponent sees the 2 unpicked jokers land in `discardedJokers` after pick.
   */
  currentOffer?: JokerOffer;
}

// ---------------------------------------------------------------------------
// Auxiliary caller-provided types
// ---------------------------------------------------------------------------

/**
 * Produced by `deck-and-claims` / `dealFresh()`, consumed by the reducer via
 * SetupComplete and JokerPicked events. Caller owns all randomness.
 *
 * Invariant: playerHand (5) + aiHand (5) + remainingDeck (10) === all 20
 * unique Cards.
 */
export interface RoundDeal {
  playerHand: Card[];
  aiHand: Card[];
  remainingDeck: Card[];
  targetRank: Rank;
  activePlayer: 'player' | 'ai';
}

// ---------------------------------------------------------------------------
// GameEvent discriminated union
// ---------------------------------------------------------------------------
//
// Every event carries `now` so the reducer never reads Date.now() directly.
// SetupComplete and JokerPicked carry caller-provided deals so randomness
// stays out of the reducer too.

export type GameEvent =
  | {
      type: 'SetupComplete';
      now: number;
      initialDeal: RoundDeal;
      musicTracks: MusicTrack[];
      /**
       * Day-5 pre-land (joker-system spec §7.1.3). Optional — if omitted,
       * the reducer default-seeds via `seedDrawPile()` (5 types × 3 copies
       * = 15 jokers). Backward-compatible with existing SetupComplete tests.
       */
      initialJokerDrawPile?: JokerType[];
    }
  | { type: 'ClaimMade'; claim: Claim; now: number }
  | { type: 'ClaimAccepted'; now: number }
  | { type: 'ChallengeCalled'; now: number }
  | { type: 'RevealComplete'; challengeWasCorrect: boolean; now: number }
  | { type: 'RoundSettled'; now: number }
  | {
      type: 'JokerPicked';
      joker: JokerType;
      nextRoundDeal: RoundDeal;
      now: number;
    }
  | { type: 'JokerOfferSkippedSessionOver'; now: number }
  | {
      type: 'Timeout';
      kind: 'active_player';
      cardIdToPlay: string;
      now: number;
    }
  | { type: 'Timeout'; kind: 'responder'; now: number }
  // -------------------------------------------------------------------------
  // Day-5 pre-land (joker-system + probe-phase). Reducer stubs in fsm.ts
  // throw InvalidTransitionError with a "pending implementation" marker
  // until the corresponding worktree fills in the transition logic.
  // -------------------------------------------------------------------------
  /**
   * joker-system spec §7.1.1 — offer a 1-of-3 joker selection to round winner.
   * `offered` length 1..3 (shrinks on pile exhaustion tail). `newDrawPile` is
   * the caller-computed updated draw pile after deduplication-by-type and
   * offer-slice removal.
   */
  | {
      type: 'JokerOffered';
      offered: JokerType[];
      newDrawPile: JokerType[];
      now: number;
    }
  /**
   * joker-system spec §7.1.1 — pile empty at offer time. Reducer transitions
   * directly to next round via caller-provided `nextRoundDeal`. Distinct from
   * `JokerOfferSkippedSessionOver` (session-over case).
   */
  | { type: 'JokerOfferEmpty'; nextRoundDeal: RoundDeal; now: number }
  /**
   * joker-system spec §7.1.1 — activate a held joker. `second_wind` is
   * NEVER used here — it auto-consumes on strike events. See spec §5.
   */
  | { type: 'UseJoker'; joker: JokerType; by: 'player' | 'ai'; now: number }
  /** probe-phase spec §7.1 — begin a Stage Whisper probe; sets Round.activeProbe. */
  | { type: 'ProbeStart'; probe: ActiveProbe; now: number }
  /**
   * probe-phase spec §7.1 — probe reveal acknowledged. Owned by joker-system
   * (declares the type) but CONSUMED by probe-phase reducer slice that
   * clears Round.activeProbe.
   */
  | { type: 'ProbeComplete'; whisperId: string; now: number }
  /** probe-phase spec §7.1 — probe timeout. Clears Round.activeProbe. */
  | { type: 'ProbeExpired'; whisperId: string; now: number };

// ---------------------------------------------------------------------------
// Error class
// ---------------------------------------------------------------------------

/**
 * Thrown by the reducer when an event isn't valid in the current Session /
 * Round state (e.g. ClaimAccepted while in `claim_phase`, any event after
 * `session_over`). Never silently no-op.
 */
export class InvalidTransitionError extends Error {
  constructor(
    public readonly currentState: string,
    public readonly eventType: string,
  ) {
    super(
      `Invalid transition: event '${eventType}' not valid in state '${currentState}'`,
    );
    this.name = 'InvalidTransitionError';
  }
}
